export const patients = [
    {
        id: 1,
        name: "Herbert",
        surname: "Müller",
        insurance: "private",
        sex: "male",
        age: 63,
    doctorIds: [],
    },

    {
  id: 2,
  name: "Anna",
  surname: "Schneider",
  insurance: "general",
  sex: "female",
  age: 54,
  doctorIds: [],
    },
    {
  id: 3,
  name: "Klaus",
  surname: "Wagner",
  insurance: "private",
  sex: "male",
  age: 71,
  doctorIds: [],
    },
    {
  id: 4,
  name: "Sabine",
  surname: "Becker",
  insurance: "general",
  sex: "female",
  age: 46,
  doctorIds: [],
    },
    {
  id: 5,
  name: "Thomas",
  surname: "Fischer",
  insurance: "private",
  sex: "male",
  age: 38,
  doctorIds: [],
    },
    {
  id: 6,
  name: "Petra",
  surname: "Hoffmann",
  insurance: "general",
  sex: "female",
  age: 67,
  doctorIds: [],
    },
    {
  id: 7,
  name: "Michael",
  surname: "Keller",
  insurance: "private",
  sex: "male",
  age: 29,
  doctorIds: [],
    },
    {
  id: 8,
  name: "Julia",
  surname: "Neumann",
  insurance: "general",
  sex: "female",
  age: 41,
  doctorIds: [],
    },
    {
  id: 9,
  name: "Ralf",
  surname: "Schulz",
  insurance: "private",
  sex: "male",
  age: 58,
  doctorIds: [],
    },
    {
  id: 10,
  name: "Monika",
  surname: "Richter",
  insurance: "general",
  sex: "female",
  age: 76,
  doctorIds: [],
    },
];

export const doctors = [
    {
  id: 1,
  name: "Heinz",
  surname: "Meyer",
  age: 52,
  doctorType: "general_practitioner",
  patientIds: [],
    },
    {
  id: 2,
  name: "Laura",
  surname: "Schmidt",
  age: 41,
  doctorType: "cardiologist",
  patientIds: [],
    },
    {
  id: 3,
  name: "Martin",
  surname: "Weber",
  age: 58,
  doctorType: "dermatologist",
  patientIds: [],
    },
    {
  id: 4,
  name: "Julia",
  surname: "Fischer",
  age: 36,
  doctorType: "orthopedist",
  patientIds: [],
    },
    {
  id: 5,
  name: "Peter",
  surname: "Becker",
  age: 47,
  doctorType: "neurologist",
  patientIds: [],
    },



]