export const patients = [
    {
        id: 1,
        name: "Herbert",
        surname: "Müller",
        insurance: "private",
        sex: "male",
        age: 63,
    doctorIds: [],
    },

    {
  id: 2,
  name: "Anna",
  surname: "Schneider",
  insurance: "general",
  sex: "female",
  age: 54,
  doctorIds: [],
    },
    {
  id: 3,
  name: "Klaus",
  surname: "Wagner",
  insurance: "private",
  sex: "male",
  age: 71,
  doctorIds: [],
    },
    {
  id: 4,
  name: "Sabine",
  surname: "Becker",
  insurance: "general",
  sex: "female",
  age: 46,
  doctorIds: [],
    },
    {
  id: 5,
  name: "Thomas",
  surname: "Fischer",
  insurance: "private",
  sex: "male",
  age: 38,
  doctorIds: [],
    },
    {
  id: 6,
  name: "Petra",
  surname: "Hoffmann",
  insurance: "general",
  sex: "female",
  age: 67,
  doctorIds: [],
    },
    {
  id: 7,
  name: "Michael",
  surname: "Keller",
  insurance: "private",
  sex: "male",
  age: 29,
  doctorIds: [],
    },
    {
  id: 8,
  name: "Julia",
  surname: "Neumann",
  insurance: "general",
  sex: "female",
  age: 41,
  doctorIds: [],
    },
    {
  id: 9,
  name: "Ralf",
  surname: "Schulz",
  insurance: "private",
  sex: "male",
  age: 58,
  doctorIds: [],
    },
    {
  id: 10,
  name: "Monika",
  surname: "Richter",
  insurance: "general",
  sex: "female",
  age: 76,
  doctorIds: [],
    },
];

export const doctors = [
  {
    id: 1,
    title: "Dr. med.",
    firstName: "Hans",
    lastName: "Müller",
    practiceName: "Praxis Müller",
    status: "active",
    rating: 4.5,
    phoneNumber: "+49 123 456789",
    email: "hans.mueller@example.com",
    website: "www.praxis-mueller.de",
    distance: 2.5,
    imageUrl: null,
    street: "Hauptstraße 10",
    postcode: "70001",
    city: "Stuttgart",
    country: "Germany",
    doctorType: { id: 1, name: "Allgemeinmedizin" },
    patientIds: [],
  },
  {
    id: 2,
    title: "Dr. med.",
    firstName: "Anna",
    lastName: "Schmidt",
    practiceName: "Kardiologen Schmidt",
    status: "active",
    rating: 4.8,
    phoneNumber: "+49 234 567890",
    email: "anna.schmidt@example.com",
    website: "www.kardiologen-schmidt.de",
    distance: 3.2,
    imageUrl: null,
    street: "Königstraße 20",
    postcode: "70002",
    city: "Stuttgart",
    country: "Germany",
    doctorType: { id: 2, name: "Kardiologie" },
    patientIds: [],
  },
  {
    id: 3,
    title: "Dr. med.",
    firstName: "Peter",
    lastName: "Weber",
    practiceName: "Dermatologie Weber",
    status: "active",
    rating: 4.3,
    phoneNumber: "+49 345 678901",
    email: "peter.weber@example.com",
    website: "www.derma-weber.de",
    distance: 1.8,
    imageUrl: null,
    street: "Neckarstraße 30",
    postcode: "70003",
    city: "Stuttgart",
    country: "Germany",
    doctorType: { id: 3, name: "Dermatologie" },
    patientIds: [],
  },
  {
    id: 4,
    title: "Dr. med.",
    firstName: "Maria",
    lastName: "Fischer",
    practiceName: "Orthopädische Klinik Fischer",
    status: "active",
    rating: 4.6,
    phoneNumber: "+49 456 789012",
    email: "maria.fischer@example.com",
    website: "www.ortho-fischer.de",
    distance: 4.1,
    imageUrl: null,
    street: "Wilhelmstraße 40",
    postcode: "70004",
    city: "Stuttgart",
    country: "Germany",
    doctorType: { id: 4, name: "Orthopädie" },
    patientIds: [],
  },
  {
    id: 5,
    title: "Dr. med.",
    firstName: "Thomas",
    lastName: "Wagner",
    practiceName: "Neurologische Praxis Wagner",
    status: "active",
    rating: 4.7,
    phoneNumber: "+49 567 890123",
    email: "thomas.wagner@example.com",
    website: "www.neuro-wagner.de",
    distance: 2.9,
    imageUrl: null,
    street: "Marketstraße 50",
    postcode: "70005",
    city: "Stuttgart",
    country: "Germany",
    doctorType: { id: 5, name: "Neurologie" },
    patientIds: [],
  },
]
